name: Release
on:
  push:
    tags:
    - "*"
jobs:
  buildx:
    name: Build & Push Multi Arch Images
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    # - name: Configure gcloud
    #   # linkerd/linkerd2-action-gcloud@v1.0.1
    #   uses: linkerd/linkerd2-action-gcloud@308c4df
    #   with:
    #     cloud_sdk_service_account_key: ${{ secrets.CLOUD_SDK_SERVICE_ACCOUNT_KEY }}
    #     gcp_project: ${{ secrets.GCP_PROJECT }}
    #     gcp_zone: ${{ secrets.GCP_ZONE }}
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Set up Docker Buildx
      # crazy-max/ghaction-docker-buildx@v3.1.0
      uses: crazy-max/ghaction-docker-buildx@373dafb
    - name: Docker Buildx (build)
      run: DOCKER_REGISTRY=docker.io/etni35 make images
    - name: Docker Buildx (push)
      run: DOCKER_REGISTRY=docker.io/etni35 make push
    - name: Docker Check Manifest
      run: DOCKER_REGISTRY=docker.io/etni35 make inspect-manifest
